name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.26"
      - name: Download dependencies
        run: go mod download
      - name: Run tests
        run: go test ./...

  app_build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.26"
      - name: Download dependencies
        run: go mod download
      - name: Build application
        run: go build ./cmd/sports

  docker_build:
    runs-on: ubuntu-latest
    needs: 
      - app_build
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build Docker image
        run: docker build -t ghcr.io/${{ github.repository }}:latest .
      - name: Docker push
        if: github.ref == 'ref/heads/main'
        run: docker push ghcr.io/${{ github.repository }}:latest