name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.26"
      - name: Download dependencies
        run: go mod download
      - name: Run tests
        run: go test ./...

  app_build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.26"
      - name: Download dependencies
        run: go mod download
      - name: Build application
        run: go build ./cmd/sports

  docker_build:
    runs-on: ubuntu-latest
    needs: 
      - app_build
    permissions:
      contents: read
      packages: write
    outputs:
      image_tag: ${{ steps.image_tag.outputs.short_sha }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set short SHA
        id: image_tag
        run: echo "short_sha=${GITHUB_SHA:0:7}" >> $GITHUB_OUTPUT
      - name: Build and Tag Docker image
        run: |
          docker build -t ghcr.io/jmar2021/sports-data-platform:latest .
          docker tag ghcr.io/jmar2021/sports-data-platform:latest ghcr.io/jmar2021/sports-data-platform:${{ steps.image_tag.outputs.short_sha }}

      - name: Docker push
        if: github.ref == 'refs/heads/main'
        run: |
          docker push ghcr.io/jmar2021/sports-data-platform:latest
          docker push ghcr.io/jmar2021/sports-data-platform:${{ steps.image_tag.outputs.short_sha }}
  
  deploy:
    runs-on: self-hosted
    needs:
      - docker_build
    permissions:
      contents: read
      packages: read
    if: github.ref == 'refs/heads/main'
    env:
      POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
      POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Pull deployment image
        env:
          IMAGE_TAG: ${{ needs.docker_build.outputs.image_tag }}
        run: docker compose -f compose.yaml pull
      - name: Deploy
        env:
          IMAGE_TAG: ${{ needs.docker_build.outputs.image_tag }}
        run: docker compose -f compose.yaml up -d
      - name: Check deployment
        run: docker compose -f compose.yaml ps